# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
#!/bin/bash
curl https://sh.rustup.rs -sSf | sudo -u vagrant HOME=/home/vagrant sh -s -- --default-toolchain stable -y 2>&1

su vagrant <<EOF
mkdir -p /home/vagrant/bindrs
ln -s /bindrs/src /home/vagrant/bindrs
ln -s /bindrs/Cargo.toml /home/vagrant/bindrs
ln -s /bindrs/Cargo.lock /home/vagrant/bindrs
ln -s /bindrs/development /home/vagrant/bindrs
EOF
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision :shell, inline: $script
  config.vm.synced_folder "..", "/bindrs"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
