# -*- mode: ruby -*-
# vi: set ft=ruby :

project_name = "bindrs"

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision :shell, inline: setup_deps
  config.vm.provision :shell, inline: setup_rust
  config.vm.provision :shell, inline: set_prompt("#{project_name.upcase}-BOX")
  config.vm.synced_folder "..", "/#{project_name}"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end

def setup_deps
  'apt-get update && apt-get install -y libssl-dev pkg-config'
end

def setup_rust
  'curl https://sh.rustup.rs -sSf | sudo -u vagrant HOME=/home/vagrant sh -s -- --default-toolchain stable -y 2>&1'
end

def set_prompt(box_name)
  %Q(echo "PS1='\\[\\033[0;32m\\]#{box_name}"'$(q=$?; [[ $q -gt 0 ]] && echo " \\[\\033[0;31m\\]$q")'" \\[\\033[0;37m\\]\\w\\[\\033[0m\\]$ '" >> /home/vagrant/.bashrc)
end
