language: rust
cache: cargo
matrix:
  include:
  - rust: stable
  - rust: beta
  - rust: nightly
    env: FEATURES=clippy
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose --features "${FEATURES}"
  - cargo test --verbose --features "${FEATURES}"
